### ISSUE TITLE
Problems in EXPORT

### ISSUE THREAD

**Issue by jtschichold** [PaloAltoNetworks/minemeld-webui#47]
2 bugs in EXPORT in the CONFIG view:

1. nodes wrapper object is missing
2. if **inputs** are not defined in the object, an empty inputs is produced.

Example:

````
ransomwaretracker_DOMBL:
  inputs:
  output: true
  prototype: ransomwaretracker.RW_DOMBL
  node_type: miner
````

Should be:

````
nodes:
  ransomwaretracker_DOMBL:
    output: true
    prototype: ransomwaretracker.RW_DOMBL
    node_type: miner
````
